#!/usr/bin/env python3
"""Generate Windower Craft recipe overrides from Mochirii Cooking data."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

RECIPE_SQL = r"""
SELECT
    r.ID, r.Cook, r.Crystal,
    r.Ingredient1, r.Ingredient2, r.Ingredient3, r.Ingredient4,
    r.Ingredient5, r.Ingredient6, r.Ingredient7, r.Ingredient8,
    r.Result, r.ResultName, COALESCE(r.content_tag, '')
FROM synth_recipes r
WHERE r.Cook > 0 AND r.Desynth = 0
ORDER BY r.ResultName, r.Cook DESC, r.ID;
"""

ITEM_ENTRY_RE = re.compile(r"^\s*\[(\d+)\]\s*=\s*\{(.*)\},?\s*$")
EN_FIELD_RE = re.compile(r'en="((?:[^"\\]|\\.)*)"')


def run_mariadb(mysql: str, database: str, sql: str) -> list[list[str]]:
    proc = subprocess.run(
        [mysql, "--batch", "--raw", "--skip-column-names", database],
        input=sql,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(f"mariadb failed: {proc.stderr.strip()}")

    return [line.split("\t") for line in proc.stdout.splitlines() if line.strip()]


def lua_unescape(value: str) -> str:
    return bytes(value, "utf-8").decode("unicode_escape")


def lua_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_windower_item_names(items_path: Path) -> dict[int, str]:
    if not items_path.is_file():
        raise SystemExit(f"missing Windower item resource: {items_path}")

    item_names: dict[int, str] = {}
    for line in items_path.read_text(encoding="utf-8", errors="replace").splitlines():
        entry_match = ITEM_ENTRY_RE.match(line)
        if not entry_match:
            continue

        en_match = EN_FIELD_RE.search(entry_match.group(2))
        if en_match:
            item_names[int(entry_match.group(1))] = lua_unescape(en_match.group(1))

    if not item_names:
        raise SystemExit(f"no item names parsed from {items_path}")

    return item_names


def int_at(row: list[str], index: int) -> int:
    value = row[index]
    return int(value) if value else 0


def recipe_key(base_name: str, seen: dict[str, int]) -> str:
    seen[base_name] += 1
    if seen[base_name] == 1:
        return base_name

    return f"{base_name} {seen[base_name]}"


def build_recipes(rows: list[list[str]], item_names: dict[int, str]) -> tuple[list[dict], list[dict]]:
    seen_names: dict[str, int] = defaultdict(int)
    recipes: list[dict] = []
    blocked: list[dict] = []

    for row in rows:
        recipe_id = int_at(row, 0)
        cook = int_at(row, 1)
        crystal_id = int_at(row, 2)
        ingredient_ids = [int_at(row, i) for i in range(3, 11) if int_at(row, i)]
        result_id = int_at(row, 11)
        result_name = row[12]
        content_tag = row[13]
        required_ids = [crystal_id, result_id, *ingredient_ids]
        missing_ids = [item_id for item_id in required_ids if item_id not in item_names]

        if missing_ids:
            blocked.append(
                {
                    "recipe_id": recipe_id,
                    "cook": cook,
                    "result_id": result_id,
                    "result_name": result_name,
                    "missing_item_ids": missing_ids,
                    "content_tag": content_tag,
                }
            )
            continue

        base_name = item_names[result_id]
        recipes.append(
            {
                "key": recipe_key(base_name, seen_names),
                "recipe_id": recipe_id,
                "cook": cook,
                "crystal_id": crystal_id,
                "crystal": item_names[crystal_id],
                "ingredient_ids": ingredient_ids,
                "ingredients": [item_names[item_id] for item_id in ingredient_ids],
                "result_id": result_id,
                "result": base_name,
                "result_name": result_name,
                "content_tag": content_tag,
            }
        )

    return recipes, blocked


def write_lua_overlay(path: Path, recipes: list[dict], source: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Generated by tools/mochirii/crafting/windower_craft_recipes.py.",
        "-- Do not edit by hand; regenerate from the live Mochirii database.",
        f"-- Generated: {source['generated_at']}",
        f"-- Database: {source['database']}",
        "",
        "return {",
    ]

    for recipe in recipes:
        lines.extend(
            [
                f"    [{lua_quote(recipe['key'])}] = {{",
                f"        crystal = {lua_quote(recipe['crystal'])},",
                "        ingredients = {",
            ]
        )
        for ingredient in recipe["ingredients"]:
            lines.append(f"            {lua_quote(ingredient)},")

        lines.extend(
            [
                "        },",
                "        mochirii = {",
                f"            recipe_id = {recipe['recipe_id']},",
                f"            cook = {recipe['cook']},",
                f"            result_id = {recipe['result_id']},",
                f"            result_name = {lua_quote(recipe['result_name'])},",
                "        },",
                "    },",
            ]
        )

    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_wrapper(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "-- Mochirii wrapper: upstream Windower Craft recipes plus live Cooking overrides.",
                "-- Do not edit by hand; see tools/mochirii/crafting/windower_craft_recipes.py.",
                "local recipes = require('recipes_upstream')",
                "local cooking = require('recipes_mochirii_cooking')",
                "",
                "for name, recipe in pairs(cooking) do",
                "    recipes[name] = recipe",
                "end",
                "",
                "return recipes",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def write_report(path: Path, report: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", default="xidb")
    parser.add_argument("--mysql", default="mariadb")
    parser.add_argument("--windower-root", default="/mnt/d/Steam/steamapps/common/FFXINA/Windower")
    parser.add_argument("--addon-dir")
    parser.add_argument("--runtime-out-dir", default="/home/xartyzx/projects/FFXI-Runtime/crafting/cooking/latest")
    parser.add_argument("--write-live", action="store_true")
    args = parser.parse_args()

    windower_root = Path(args.windower_root)
    addon_dir = Path(args.addon_dir) if args.addon_dir else windower_root / "addons" / "craft"
    runtime_dir = Path(args.runtime_out_dir)
    items_path = windower_root / "res" / "items.lua"
    item_names = load_windower_item_names(items_path)
    rows = run_mariadb(args.mysql, args.database, RECIPE_SQL)
    recipes, blocked = build_recipes(rows, item_names)
    now = datetime.now(timezone.utc).isoformat()
    source = {
        "generated_at": now,
        "database": args.database,
        "windower_items": str(items_path),
    }

    report = {
        **source,
        "summary": {
            "active_cooking_recipes": len(rows),
            "generated_cooking_recipes": len(recipes),
            "blocked_recipes": len(blocked),
            "endgame_generated_recipes": sum(1 for recipe in recipes if recipe["cook"] >= 90),
        },
        "recipe_overlay": str(addon_dir / "recipes_mochirii_cooking.lua"),
        "recipes": recipes,
        "blocked": blocked,
    }

    write_report(runtime_dir / "windower_craft_cooking_recipes.json", report)
    write_lua_overlay(runtime_dir / "recipes_mochirii_cooking.lua", recipes, source)

    if args.write_live:
        write_lua_overlay(addon_dir / "recipes_mochirii_cooking.lua", recipes, source)
        write_wrapper(addon_dir / "recipes.lua")

    print(json.dumps(report["summary"], indent=2, sort_keys=True))
    if blocked:
        print(f"Blocked {len(blocked)} recipe(s); see {runtime_dir / 'windower_craft_cooking_recipes.json'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
