#!/usr/bin/env python3
"""Generate and audit Mochirii's implementation-aware content registry."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
from pathlib import Path
from typing import Any

REGISTRY_PATH = Path("documentation/data/mochirii_content_parity.json")
LUA_PATH = Path("modules/custom/lua/twills_content_parity_registry.lua")
ALLOWED_STATUSES = {
    "verified",
    "unverified",
    "partial",
    "skeleton",
    "absent",
    "monthly",
}


def lua_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return f"'{escaped}'"


def to_lua(value: Any, indent: int = 0) -> str:
    prefix = " " * indent
    child = " " * (indent + 4)
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return lua_string(value)
    if isinstance(value, list):
        if not value:
            return "{}"
        rows = [f"{child}{to_lua(item, indent + 4)}," for item in value]
        return "{\n" + "\n".join(rows) + f"\n{prefix}}}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = []
        for key in sorted(value):
            key_text = (
                key
                if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key)
                else f"[{lua_string(key)}]"
            )
            rows.append(f"{child}{key_text} = {to_lua(value[key], indent + 4)},")
        return "{\n" + "\n".join(rows) + f"\n{prefix}}}"
    raise TypeError(f"unsupported registry value: {type(value)!r}")


def load_registry(repo_root: Path) -> dict[str, Any]:
    path = repo_root / REGISTRY_PATH
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schemaVersion") != 1:
        raise ValueError("content registry schemaVersion must be 1")
    if set(data.get("allowedStatuses", [])) != ALLOWED_STATUSES:
        raise ValueError(
            "content registry allowedStatuses does not match the supported policy"
        )

    systems = data.get("systems")
    if not isinstance(systems, list) or not systems:
        raise ValueError("content registry must define systems")

    seen: set[str] = set()
    for system in systems:
        key = system.get("key")
        status = system.get("status")
        if not isinstance(key, str) or not re.fullmatch(r"[a-z0-9_]+", key):
            raise ValueError(f"invalid content registry key: {key!r}")
        if key in seen:
            raise ValueError(f"duplicate content registry key: {key}")
        if status not in ALLOWED_STATUSES:
            raise ValueError(f"invalid status for {key}: {status!r}")
        if not system.get("reason") or not system.get("repairPolicy"):
            raise ValueError(f"registry entry {key} is missing reason or repairPolicy")
        seen.add(key)
    return data


def render_lua(data: dict[str, Any]) -> str:
    by_key = {entry["key"]: entry for entry in data["systems"]}
    generated = {
        "schemaVersion": data["schemaVersion"],
        "allowedStatuses": data["allowedStatuses"],
        "systems": by_key,
    }
    return (
        "-----------------------------------\n"
        "-- Generated from documentation/data/mochirii_content_parity.json.\n"
        "-- Do not edit this file directly; run tools/mochirii/content_parity_registry.py.\n"
        "-----------------------------------\n"
        f"return {to_lua(generated)}\n"
    )


def scan_source(repo_root: Path) -> dict[str, Any]:
    atma_path = repo_root / "scripts/globals/abyssea/atma.lua"
    atma_text = atma_path.read_text(encoding="utf-8")
    atma_rows = re.findall(
        r"\[xi\.ki\.(ATMA_OF_[A-Z0-9_]+)\]\s*=\s*\{([^}]*)\}", atma_text
    )
    empty_atma = sorted(name for name, body in atma_rows if not body.strip())

    mission_root = repo_root / "scripts/missions"
    mission_skeletons = sorted(
        str(path.relative_to(repo_root)).replace("\\", "/")
        for path in mission_root.rglob("*.lua")
        if "TODO: Add zones and interactions"
        in path.read_text(encoding="utf-8", errors="ignore")
    )
    quest_root = repo_root / "scripts/quests"
    quest_todos = sorted(
        str(path.relative_to(repo_root)).replace("\\", "/")
        for path in quest_root.rglob("*.todo")
    )
    empty_quest_sections = sorted(
        str(path.relative_to(repo_root)).replace("\\", "/")
        for path in quest_root.rglob("*.lua")
        if re.search(
            r"quest\.sections\s*=\s*\{\s*\}",
            path.read_text(encoding="utf-8", errors="ignore"),
        )
    )

    try:
        commit = subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        commit = "unknown"

    return {
        "commit": commit,
        "atmaDefinitions": len(atma_rows),
        "emptyAtmaDefinitions": empty_atma,
        "missionInteractionSkeletons": mission_skeletons,
        "questTodoFiles": quest_todos,
        "emptyQuestSections": empty_quest_sections,
    }


def write_report(
    report_dir: Path, registry: dict[str, Any], scan: dict[str, Any]
) -> tuple[Path, Path]:
    report_dir.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
    payload = {
        "schemaVersion": 1,
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "registry": registry,
        "sourceScan": scan,
    }
    json_path = report_dir / f"mochirii-content-parity-{stamp}.json"
    md_path = report_dir / f"mochirii-content-parity-{stamp}.md"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Mochirii Content Parity Report",
        "",
        f"- Commit: `{scan['commit']}`",
        f"- Atma definitions: `{scan['atmaDefinitions']}`",
        f"- Empty Atma definitions: `{len(scan['emptyAtmaDefinitions'])}`",
        f"- Mission interaction skeletons: `{len(scan['missionInteractionSkeletons'])}`",
        f"- Quest `.todo` files: `{len(scan['questTodoFiles'])}`",
        f"- Empty quest sections: `{len(scan['emptyQuestSections'])}`",
        "",
        "## Systems",
        "",
        "| System | Status | Repair policy |",
        "| --- | --- | --- |",
    ]
    for system in registry["systems"]:
        lines.append(
            f"| {system['name']} | `{system['status']}` | `{system['repairPolicy']}` |"
        )
    lines.extend(["", "## Dynamic Blockers", ""])
    for name in scan["emptyAtmaDefinitions"]:
        lines.append(f"- Empty Atma effect: `{name}`")
    for path in scan["missionInteractionSkeletons"]:
        lines.append(f"- Mission interaction skeleton: `{path}`")
    for path in scan["questTodoFiles"]:
        lines.append(f"- Quest todo: `{path}`")
    for path in scan["emptyQuestSections"]:
        lines.append(f"- Empty quest sections: `{path}`")
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return json_path, md_path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report-dir", type=Path)
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    registry = load_registry(repo_root)
    rendered = render_lua(registry)
    lua_path = repo_root / LUA_PATH

    if args.check:
        current = lua_path.read_text(encoding="utf-8") if lua_path.exists() else ""
        if current != rendered:
            raise SystemExit(f"generated registry is stale: {LUA_PATH}")
    else:
        lua_path.parent.mkdir(parents=True, exist_ok=True)
        lua_path.write_text(rendered, encoding="utf-8", newline="\n")

    scan = scan_source(repo_root)
    if args.report_dir:
        json_path, md_path = write_report(args.report_dir.resolve(), registry, scan)
        print(json_path)
        print(md_path)
    else:
        print(
            json.dumps(
                {
                    "systems": len(registry["systems"]),
                    "atmaDefinitions": scan["atmaDefinitions"],
                    "emptyAtmaDefinitions": len(scan["emptyAtmaDefinitions"]),
                    "missionInteractionSkeletons": len(
                        scan["missionInteractionSkeletons"]
                    ),
                    "questTodoFiles": len(scan["questTodoFiles"]),
                    "emptyQuestSections": len(scan["emptyQuestSections"]),
                },
                sort_keys=True,
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
